[project]
name = "blank-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "binance-connector>=3.12.0",
    "plotly>=5.24.1",
    "streamlit>=1.41.1",
    "ta-lib>=0.6.1",
]
